### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by wuqiulin1995** [ESOS-Lab/Mobibench#1]
Is this must be used by cross-compile and cannot be used on desktop?

**Comment by resourceful** [comment]
If you are to measure the performance in the Android mobile then it must be crossed compiled. But if you are to use it in the Linux system, it also provides command line tool. 
Look under "shell" directory in the repository.

**Comment by wuqiulin1995** [comment]
Hi

Can I specify a device (e.g. /dev/sdb) to measure its performance in Ubuntu?

**Comment by wuqiulin1995** [comment]
Hi

Can I specify a device (e.g. /dev/sdb) to measure its performance in Ubuntu?

**Comment by resourceful** [comment]
If you are testing on Ubuntu with shell version of Mobibench, the path can be specified via `-p` option.  ([list of options](https://github.com/ESOS-Lab/Mobibench#usage-shell-version))

**Comment by wuqiulin1995** [comment]
I have used the -p option but it shows 

-----------------------------------------
[mobibench measurement setup]
-----------------------------------------
File size per thread : 1024 KB
IO size : 4 KB
IO count : 256 
Access Mode 0, Sync Mode 0
num of Threads : 1
setState: 1
open block device : /dev/sdb

File write error!!! [no: 28, pos: 20971520]
setState: 4
setState: 2
Err string : File write error

**Comment by resourceful** [comment]
The message shows that it had no problem opening the device but failed while writing to it. So, you need to check the permission, mount status, etc. for writing to the raw device.

**Comment by wuqiulin1995** [comment]
OK 
I'll try it. Thank you.

**Comment by wuqiulin1995** [comment]
HI
If I mount f2fs filesystem to the "/home/ubuntu/f2fs" directory,  and I want to measure the performance of it.
Should the -p option be set as "/home/ubuntu/f2fs"?

**Comment by resourceful** [comment]
Yes, you are right. `mobibench -p /home/ubuntu/f2fs` or you can specify a file name `mobibench -p /home/ubuntu/f2fs/testfile`

**Comment by wuqiulin1995** [comment]
OK 
Thanks a lot

**Comment by wuqiulin1995** [comment]
Hi

I use mobibench -a 3 to measure the random read, but the result shows that it only has 3.8MB/sec, but if I use the -a 1, the random write has 110MB/sec, why there is such a great gap?

sudo mobibench -f 160000 -r 16 -a 3
-----------------------------------------
[mobibench measurement setup]
-----------------------------------------
File size per thread : 160000 KB
IO size : 16 KB
IO count : 10000 
Access Mode 3, Sync Mode 0
 of Threads : 1
setState: 1
setState: 2
-----------------------------------------
[Messurement Result]
-----------------------------------------
[CPU] : Active,Idle,IoWait : 6.65 0.00 93.35
[TIME] :      40 sec 997185us. 	3996372 B/sec, 	3902.71 KB/sec, 	3.81 MB/sec. 243.92 IOPS(16KB) 
[CON SWITCHES] : 7614 7346
setState: 3
Err string : No error
-----------------------------------------




sudo mobibench -f 160000 -r 16 -a 1
-----------------------------------------
[mobibench measurement setup]
-----------------------------------------
File size per thread : 160000 KB
IO size : 16 KB
IO count : 10000 
Access Mode 1, Sync Mode 0
 of Threads : 1
setState: 1
setState: 2
-----------------------------------------
[Messurement Result]
-----------------------------------------
[CPU] : Active,Idle,IoWait : 8.85 0.00 91.15
[TIME] :       1 sec 409079us. 	116274531 B/sec, 	113549.35 KB/sec, 	110.89 MB/sec. 7096.83 IOPS(16KB) 
[CON SWITCHES] : 241 123
setState: 3
Err string : No error
-----------------------------------------

**Comment by resourceful** [comment]
It is very hard to tell with your description of the test. The result may vary depending on a storage medium you use to test. One reason for the random write performance to be faster than the random read is that all the writes can be stored in the page cache, whereas the randomly read data has to be actually be fetched from the storage medium.

**Comment by wuqiulin1995** [comment]
Hi 
The message shows that "open failed 0"

What's the problem about?

**Comment by resourceful** [comment]
Please check permission of your mounted device and the directory

**Comment by wuqiulin1995** [comment]
OK 
Thanks a lot!

**Comment by wuqiulin1995** [comment]
Hi 
I did cross compile and used it on an Android development board, it shoes like that

hikey960:/data # mobibench -p /data/mobibench -a 1
-----------------------------------------
[mobibench measurement setup]
-----------------------------------------
File size per thread : 1024 KB
IO size : 4 KB
IO count : 256 
Access Mode 1, Sync Mode 0
of Threads : 1
setState: 1
setState: 2
Segmentation fault 

What's the problem about?

**Comment by resourceful** [comment]
if you could run strace, gdb, or any other primitive methods to narrow down the problem it would be better. It is very hard to tell with given information

**Comment by resourceful** [comment]
And, I believe the subject you are asking is beyond the scope of the title you have given to this issue. So I suggest closing the issue.

**Comment by wuqiulin1995** [comment]
OK, I 'll check it .
